### ISSUE TITLE
Expose other language options

### ISSUE THREAD

**Issue by LovecraftianHorror** [LovecraftianHorror/subwinder#12]
Currently this library only exposes some of the information from the API in English (such as the long language names): however, it would be best to expose other languages as well. This could be done with some mild tweaking to the `lang` module as well as changing the endpoints to give the option to pass in other languages (or maybe pass it in to the whole `SubWinder` or `AuthSubWinder` class).

**Comment by CosmicHorrorDev** [comment]
Thinking back on it now, I don't really think this will be very useful so I'm just gonna close this
