### ISSUE TITLE
Feature: Add in type hinting for functions and methods

### ISSUE THREAD

**Issue by LovecraftianHorror** [LovecraftianHorror/subwinder#35]
## Feature Request

- [ ] Expose functionality from the API
- [x] Add extra functionality in the library
- [ ] Other: 

### Description

It would be nice to try out `typing`'s type hinting. It's not strictly enforced, but it gives a good reference for what things should be which should be nice for both developing on and using the library.

**Comment by LovecraftianHorror** [comment]
There's a branch that's got a decent amount of the work done for implementing this using `mypy`, but it's currently stalled for reasons that I'll cover in more detail when I feel like it.

**Comment by CosmicHorrorDev** [comment]
This should be all done with a recent branch. I'm currently using `pyright`, but hopefully things work more or less with `mypy` too
