### ISSUE TITLE
Feature: Send password as MD5 hash

### ISSUE THREAD

**Issue by LovecraftianHorror** [LovecraftianHorror/subwinder#48]
## Feature Request

- [ ] Expose functionality from the API
- [x] Add extra functionality in the library
- [ ] Other: 

### Description

The api docs mention for security to use HTTPS and/or send the password as the MD5 hash. I've heard mixed things on sending the hash versus the password, but there's no reason not to since it's trying to enforce sending out the password in case it gets forced back to HTTP somehow.

**Comment by GrantEthanEckstein** [comment]
Addressed with #49

**Comment by LovecraftianHorror** [comment]
As a follow up it would be good to expose an additional env var for this `OPEN_SUBTITLES_PASSWORD_HASH` or something along those lines. This would allow an alternative to passing in the password with env vars as well

**Comment by LovecraftianHorror** [comment]
Implemented in f056560375f92151ac70bb3353ba9bd32860e0d8
