### ISSUE TITLE
Other: Switching `.download_subtitles(...)` to write bytes is less error prone

### ISSUE THREAD

**Issue by LovecraftianHorror** [LovecraftianHorror/subwinder#50]
### Description

Currently, there can be a problem when the author specified the wrong encoding on subtitles when uploading causing `utils.extract(...)` to fail currently (which is used by `.dowload_subtitles(...)` and `.preview_subtitles(...)`. However, only `.preview_subtitles(...)` makes sense for needing to extract the string while `.download_subtitles(...)` can just directly write the bytes to a file.

For this reason, it makes sense to switch extract to return bytes and decode within just `.preview_subtitles(...)`. It would also be nice to try and provide a fallback for failing encoding. Right now I've only seen `UnicodeDecodeError`, but it would be nice to have a common error to look for.

**Comment by LovecraftianHorror** [comment]
Switching `extract` to not deal with the encoding so that things can be downloaded directly occurred in 97112d7cde4b3579dba4584c748a73fe77cdb2de.

**Comment by LovecraftianHorror** [comment]
So the other portion here is to work on falling back to trying to detect the character encoding from the contents. There seems to be a couple libraries here which we could include one of as an optional dependency. The ones I saw where `chardet` and `cchardet`. The former being a full python reimplementation, while the latter is bindings to the original cpp library. The bindings are of course much faster: however, they aren't supported in some environments (`pyenv` and `anaconda`) so I'm a bit hesitant there. To really decide I think I'll have to benchmark `cchardet` to see just how slow it really is, ideally you won't need to fall back to it very often unless you're seeing lots of previews from authors that incorrectly denoted the encoding.

**Comment by CosmicHorrorDev** [comment]
I think that it would be better for the character encoding detection stuff to be in a separate issue at this point since I always get confused by the original title
